import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-foodservice-manufacturer-broker-commission-audit",
  "engine": "recovery",
  "title": "Foodservice Manufacturer Broker Commission Audit",
  "shortTitle": "Foodservice Manufacturer Broker Commission Audit",
  "tagline": "Audit broker commissions against territories, products, customers, net sales, exclusions, and contractual rates.",
  "industry": "Foodservice Commercial Finance",
  "buyer": "Food manufacturers and broker networks",
  "uiPort": 4707,
  "apiPort": 5707,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Foodservice Manufacturer Broker Commission Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments in one accountable workflow. Audit broker commissions against territories, products, customers, net sales, exclusions, and contractual rates.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Foodservice Manufacturer Broker Commission Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("broker-agreement-library","FMB01","Broker agreement library","Execute broker agreement library using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed broker agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Broker agreement library Reference","text","FMB01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("territory-customer-mapping","FMB02","Territory customer mapping","Execute territory customer mapping using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed territory customer mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Territory customer mapping Reference","text","FMB02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("product-eligibility-registry","FMB03","Product eligibility registry","Execute product eligibility registry using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed product eligibility registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Product eligibility registry Reference","text","FMB03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("distributor-depletion-ingestion","FMB04","Distributor depletion ingestion","Execute distributor depletion ingestion using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed distributor depletion ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Distributor depletion ingestion Reference","text","FMB04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("gross-sales-calculation","FMB05","Gross sales calculation","Execute gross sales calculation using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed gross sales calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Gross sales calculation Reference","text","FMB05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("returns-deduction","FMB06","Returns deduction","Execute returns deduction using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed returns deduction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Returns deduction Reference","text","FMB06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("promotion-exclusion","FMB07","Promotion exclusion","Execute promotion exclusion using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed promotion exclusion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Promotion exclusion Reference","text","FMB07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("net-sales-calculation","FMB08","Net sales calculation","Execute net sales calculation using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed net sales calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Net sales calculation Reference","text","FMB08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("commission-tier-calculation","FMB09","Commission tier calculation","Execute commission tier calculation using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed commission tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Commission tier calculation Reference","text","FMB09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("draw-recovery-control","FMB10","Draw recovery control","Execute draw recovery control using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed draw recovery control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Draw recovery control Reference","text","FMB10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("statement-reconciliation","FMB11","Statement reconciliation","Execute statement reconciliation using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed statement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Statement reconciliation Reference","text","FMB11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("duplicate-commission-detection","FMB12","Duplicate commission detection","Execute duplicate commission detection using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed duplicate commission detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Duplicate commission detection Reference","text","FMB12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("broker-dispute-workflow","FMB13","Broker dispute workflow","Execute broker dispute workflow using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed broker dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Broker dispute workflow Reference","text","FMB13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("payment-correction","FMB14","Payment correction","Execute payment correction using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed payment correction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Payment correction Reference","text","FMB14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]}),
feature("broker-territory-analytics","FMB15","Broker territory analytics","Execute broker territory analytics using broker agreements, territories, customers, distributor depletion, net sales, exclusions, commission rates, draws, statements, and payments.","Produce a governed broker territory analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Broker / Product Territory","text","Broker / Product Territory · Standard Case"],["caseReference","Broker territory analytics Reference","text","FMB15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1387500],["supportedAmount","Evidence-Supported Amount","currency",1165500],["domainDriver","Commission Basis","select","Gross sales",["Gross sales","Net sales","Depletion volume"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Broker agreement library case","Territory customer mapping case","Product eligibility registry case","Distributor depletion ingestion case","Gross sales calculation case"]})
]);
